// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart_items.sql

package db

import (
	"context"
)

const countCartItems = `-- name: CountCartItems :one
SELECT COUNT(*) FROM cart_items WHERE cart_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCartItems(ctx context.Context, cartID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countCartItems, cartID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCartItem = `-- name: CreateCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, cart_id, product_id, quantity, created_at, updated_at, deleted_at
`

type CreateCartItemParams struct {
	CartID    int32 `json:"cart_id"`
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, createCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, cart_id, product_id, quantity, created_at, updated_at, deleted_at FROM cart_items
WHERE cart_id = $1 AND product_id = $2 AND deleted_at IS NULL
`

type GetCartItemParams struct {
	CartID    int32 `json:"cart_id"`
	ProductID int32 `json:"product_id"`
}

func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCartItemByID = `-- name: GetCartItemByID :one
SELECT id, cart_id, product_id, quantity, created_at, updated_at, deleted_at FROM cart_items
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCartItemByID(ctx context.Context, id int32) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByID, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, cart_id, product_id, quantity, created_at, updated_at, deleted_at FROM cart_items
WHERE cart_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListCartItems(ctx context.Context, cartID int32) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCartItem = `-- name: RestoreCartItem :one
UPDATE cart_items
SET quantity = $3, deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE cart_id = $1 AND product_id = $2 AND deleted_at IS NOT NULL
RETURNING id, cart_id, product_id, quantity, created_at, updated_at, deleted_at
`

type RestoreCartItemParams struct {
	CartID    int32 `json:"cart_id"`
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) RestoreCartItem(ctx context.Context, arg RestoreCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, restoreCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCartItem = `-- name: SoftDeleteCartItem :exec
UPDATE cart_items
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCartItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteCartItem, id)
	return err
}

const softDeleteCartItemsByCartID = `-- name: SoftDeleteCartItemsByCartID :exec
UPDATE cart_items
SET deleted_at = CURRENT_TIMESTAMP
WHERE cart_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCartItemsByCartID(ctx context.Context, cartID int32) error {
	_, err := q.db.Exec(ctx, softDeleteCartItemsByCartID, cartID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, cart_id, product_id, quantity, created_at, updated_at, deleted_at
`

type UpdateCartItemQuantityParams struct {
	ID       int32 `json:"id"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (cart_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (cart_id, product_id)
DO UPDATE SET
    quantity = cart_items.quantity + EXCLUDED.quantity,
    deleted_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE cart_items.deleted_at IS NOT NULL
RETURNING id, cart_id, product_id, quantity, created_at, updated_at, deleted_at
`

type UpsertCartItemParams struct {
	CartID    int32 `json:"cart_id"`
	ProductID int32 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem, arg.CartID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
