// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package db

import (
	"context"
)

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, updated_at, deleted_at
`

func (q *Queries) CreateCart(ctx context.Context, userID int32) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, user_id, created_at, updated_at, deleted_at FROM carts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCartByID(ctx context.Context, id int32) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByID, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, created_at, updated_at, deleted_at FROM carts
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID int32) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCart = `-- name: SoftDeleteCart :exec
UPDATE carts
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCart(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteCart, id)
	return err
}

const softDeleteCartByUserID = `-- name: SoftDeleteCartByUserID :exec
UPDATE carts
SET deleted_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCartByUserID(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, softDeleteCartByUserID, userID)
	return err
}

const updateCartTimestamp = `-- name: UpdateCartTimestamp :one
UPDATE carts
SET updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateCartTimestamp(ctx context.Context, id int32) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartTimestamp, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
