// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO order_idempotency_keys (user_id, idempotency_key, order_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, idempotency_key, order_id, created_at
`

type CreateIdempotencyKeyParams struct {
	UserID         int32       `json:"user_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	OrderID        pgtype.Int4 `json:"order_id"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (OrderIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey, arg.UserID, arg.IdempotencyKey, arg.OrderID)
	var i OrderIdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, user_id, idempotency_key, order_id, created_at FROM order_idempotency_keys
WHERE user_id = $1 AND idempotency_key = $2
`

type GetIdempotencyKeyParams struct {
	UserID         int32  `json:"user_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (OrderIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i OrderIdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}

const updateIdempotencyKeyOrderID = `-- name: UpdateIdempotencyKeyOrderID :exec
UPDATE order_idempotency_keys
SET order_id = $3
WHERE user_id = $1 AND idempotency_key = $2
`

type UpdateIdempotencyKeyOrderIDParams struct {
	UserID         int32       `json:"user_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	OrderID        pgtype.Int4 `json:"order_id"`
}

func (q *Queries) UpdateIdempotencyKeyOrderID(ctx context.Context, arg UpdateIdempotencyKeyOrderIDParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyKeyOrderID, arg.UserID, arg.IdempotencyKey, arg.OrderID)
	return err
}
