// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrderItems = `-- name: CountOrderItems :one
SELECT COUNT(*) FROM order_items WHERE order_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountOrderItems(ctx context.Context, orderID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderItems, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price, created_at, deleted_at
`

type CreateOrderItemParams struct {
	OrderID   int32          `json:"order_id"`
	ProductID int32          `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT id, order_id, product_id, quantity, price, created_at, deleted_at FROM order_items
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrderItemByID(ctx context.Context, id int32) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItemByID, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrderTotal = `-- name: GetOrderTotal :one
SELECT COALESCE(SUM(quantity * price), 0)::DECIMAL(10,2) as total
FROM order_items
WHERE order_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrderTotal(ctx context.Context, orderID int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getOrderTotal, orderID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, quantity, price, created_at, deleted_at FROM order_items
WHERE order_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID int32) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrderItem = `-- name: SoftDeleteOrderItem :exec
UPDATE order_items
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrderItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteOrderItem, id)
	return err
}

const softDeleteOrderItemsByOrderID = `-- name: SoftDeleteOrderItemsByOrderID :exec
UPDATE order_items
SET deleted_at = CURRENT_TIMESTAMP
WHERE order_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrderItemsByOrderID(ctx context.Context, orderID int32) error {
	_, err := q.db.Exec(ctx, softDeleteOrderItemsByOrderID, orderID)
	return err
}
