// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, url, alt_text, is_primary)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, url, alt_text, is_primary, created_at, deleted_at
`

type CreateProductImageParams struct {
	ProductID int32       `json:"product_id"`
	Url       string      `json:"url"`
	AltText   pgtype.Text `json:"alt_text"`
	IsPrimary pgtype.Bool `json:"is_primary"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.Url,
		arg.AltText,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPrimaryProductImage = `-- name: GetPrimaryProductImage :one
SELECT id, product_id, url, alt_text, is_primary, created_at, deleted_at FROM product_images
WHERE product_id = $1 AND is_primary = true AND deleted_at IS NULL
`

func (q *Queries) GetPrimaryProductImage(ctx context.Context, productID int32) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getPrimaryProductImage, productID)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductImageByID = `-- name: GetProductImageByID :one
SELECT id, product_id, url, alt_text, is_primary, created_at, deleted_at FROM product_images
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductImageByID(ctx context.Context, id int32) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getProductImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, url, alt_text, is_primary, created_at, deleted_at FROM product_images
WHERE product_id = $1 AND deleted_at IS NULL
ORDER BY is_primary DESC, created_at ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID int32) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.AltText,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImagesByProductIDs = `-- name: ListProductImagesByProductIDs :many
SELECT id, product_id, url, alt_text, is_primary, created_at, deleted_at FROM product_images
WHERE product_id = ANY($1::int[]) AND deleted_at IS NULL
ORDER BY product_id, is_primary DESC, created_at ASC
`

func (q *Queries) ListProductImagesByProductIDs(ctx context.Context, dollar_1 []int32) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImagesByProductIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.AltText,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryProductImage = `-- name: SetPrimaryProductImage :exec
UPDATE product_images
SET is_primary = CASE WHEN id = $2 THEN true ELSE false END
WHERE product_id = $1 AND deleted_at IS NULL
`

type SetPrimaryProductImageParams struct {
	ProductID int32 `json:"product_id"`
	ID        int32 `json:"id"`
}

func (q *Queries) SetPrimaryProductImage(ctx context.Context, arg SetPrimaryProductImageParams) error {
	_, err := q.db.Exec(ctx, setPrimaryProductImage, arg.ProductID, arg.ID)
	return err
}

const softDeleteProductImage = `-- name: SoftDeleteProductImage :exec
UPDATE product_images
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProductImage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteProductImage, id)
	return err
}

const softDeleteProductImagesByProductID = `-- name: SoftDeleteProductImagesByProductID :exec
UPDATE product_images
SET deleted_at = CURRENT_TIMESTAMP
WHERE product_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProductImagesByProductID(ctx context.Context, productID int32) error {
	_, err := q.db.Exec(ctx, softDeleteProductImagesByProductID, productID)
	return err
}

const updateProductImage = `-- name: UpdateProductImage :one
UPDATE product_images
SET url = $2, alt_text = $3, is_primary = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, product_id, url, alt_text, is_primary, created_at, deleted_at
`

type UpdateProductImageParams struct {
	ID        int32       `json:"id"`
	Url       string      `json:"url"`
	AltText   pgtype.Text `json:"alt_text"`
	IsPrimary pgtype.Bool `json:"is_primary"`
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, updateProductImage,
		arg.ID,
		arg.Url,
		arg.AltText,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.AltText,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
