// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveProducts(ctx context.Context) (int64, error)
	CountCartItems(ctx context.Context, cartID int32) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountOrderItems(ctx context.Context, orderID int32) (int64, error)
	CountOrders(ctx context.Context) (int64, error)
	CountOrdersByStatus(ctx context.Context, status NullOrderStatus) (int64, error)
	CountOrdersByUserID(ctx context.Context, userID int32) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountProductsByCategory(ctx context.Context, categoryID int32) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCart(ctx context.Context, userID int32) (Cart, error)
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteRefreshTokensByUserID(ctx context.Context, userID int32) error
	GetCartByID(ctx context.Context, id int32) (Cart, error)
	GetCartByUserID(ctx context.Context, userID int32) (Cart, error)
	GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error)
	GetCartItemByID(ctx context.Context, id int32) (CartItem, error)
	GetCategoriesByIDs(ctx context.Context, dollar_1 []int32) ([]Category, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	GetOrderItemByID(ctx context.Context, id int32) (OrderItem, error)
	GetOrderTotal(ctx context.Context, orderID int32) (pgtype.Numeric, error)
	GetPrimaryProductImage(ctx context.Context, productID int32) (ProductImage, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	GetProductBySKU(ctx context.Context, sku string) (Product, error)
	GetProductImageByID(ctx context.Context, id int32) (ProductImage, error)
	GetProductsByIDs(ctx context.Context, dollar_1 []int32) ([]Product, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetRefreshTokensByUserID(ctx context.Context, userID int32) ([]RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListActiveCategories(ctx context.Context) ([]Category, error)
	ListActiveProducts(ctx context.Context, arg ListActiveProductsParams) ([]Product, error)
	ListCartItems(ctx context.Context, cartID int32) ([]CartItem, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListOrderItems(ctx context.Context, orderID int32) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]Order, error)
	ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error)
	ListProductImages(ctx context.Context, productID int32) ([]ProductImage, error)
	ListProductImagesByProductIDs(ctx context.Context, dollar_1 []int32) ([]ProductImage, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SetPrimaryProductImage(ctx context.Context, arg SetPrimaryProductImageParams) error
	SoftDeleteCart(ctx context.Context, id int32) error
	SoftDeleteCartByUserID(ctx context.Context, userID int32) error
	SoftDeleteCartItem(ctx context.Context, id int32) error
	SoftDeleteCartItemsByCartID(ctx context.Context, cartID int32) error
	SoftDeleteCategory(ctx context.Context, id int32) error
	SoftDeleteOrder(ctx context.Context, id int32) error
	SoftDeleteOrderItem(ctx context.Context, id int32) error
	SoftDeleteOrderItemsByOrderID(ctx context.Context, orderID int32) error
	SoftDeleteProduct(ctx context.Context, id int32) error
	SoftDeleteProductImage(ctx context.Context, id int32) error
	SoftDeleteProductImagesByProductID(ctx context.Context, productID int32) error
	SoftDeleteUser(ctx context.Context, id int32) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateCartTimestamp(ctx context.Context, id int32) (Cart, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryStatus(ctx context.Context, arg UpdateCategoryStatusParams) (Category, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) (ProductImage, error)
	UpdateProductStatus(ctx context.Context, arg UpdateProductStatusParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
