// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	db "github.com/trenchesdeveloper/go-ai-store/db/sqlc"
	"github.com/trenchesdeveloper/go-ai-store/internal/dto"
)

type CreateOrderInput struct {
	ShippingAddress string  `json:"shippingAddress"`
	IdempotencyKey  *string `json:"idempotencyKey,omitempty"`
}

type Mutation struct {
}

type OrderConnection struct {
	Edges    []*OrderEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type OrderEdge struct {
	Node *dto.OrderResponse `json:"node"`
}

type PageInfo struct {
	Page       int32 `json:"page"`
	Limit      int32 `json:"limit"`
	Total      int32 `json:"total"`
	TotalPages int32 `json:"totalPages"`
}

type ProductConnection struct {
	Edges    []*ProductEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ProductEdge struct {
	Node *dto.ProductResponse `json:"node"`
}

type Query struct {
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refreshToken"`
}

type UpdateOrderStatusInput struct {
	Status db.OrderStatus `json:"status"`
}
