package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/trenchesdeveloper/go-ai-store/graph"
	"github.com/trenchesdeveloper/go-ai-store/internal/dto"
)

// Quantity is the resolver for the quantity field.
func (r *addToCartInputResolver) Quantity(ctx context.Context, obj *dto.AddToCartRequest, data int32) error {
	panic(fmt.Errorf("not implemented: Quantity - quantity"))
}

// Stock is the resolver for the stock field.
func (r *createProductInputResolver) Stock(ctx context.Context, obj *dto.CreateProductRequest, data int32) error {
	panic(fmt.Errorf("not implemented: Stock - stock"))
}

// Quantity is the resolver for the quantity field.
func (r *updateCartItemInputResolver) Quantity(ctx context.Context, obj *dto.UpdateCartItemRequest, data int32) error {
	panic(fmt.Errorf("not implemented: Quantity - quantity"))
}

// Stock is the resolver for the stock field.
func (r *updateProductInputResolver) Stock(ctx context.Context, obj *dto.UpdateProductRequest, data int32) error {
	panic(fmt.Errorf("not implemented: Stock - stock"))
}

// AddToCartInput returns graph.AddToCartInputResolver implementation.
func (r *Resolver) AddToCartInput() graph.AddToCartInputResolver { return &addToCartInputResolver{r} }

// CreateProductInput returns graph.CreateProductInputResolver implementation.
func (r *Resolver) CreateProductInput() graph.CreateProductInputResolver {
	return &createProductInputResolver{r}
}

// UpdateCartItemInput returns graph.UpdateCartItemInputResolver implementation.
func (r *Resolver) UpdateCartItemInput() graph.UpdateCartItemInputResolver {
	return &updateCartItemInputResolver{r}
}

// UpdateProductInput returns graph.UpdateProductInputResolver implementation.
func (r *Resolver) UpdateProductInput() graph.UpdateProductInputResolver {
	return &updateProductInputResolver{r}
}

type addToCartInputResolver struct{ *Resolver }
type createProductInputResolver struct{ *Resolver }
type updateCartItemInputResolver struct{ *Resolver }
type updateProductInputResolver struct{ *Resolver }
