package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/trenchesdeveloper/go-ai-store/graph"
	"github.com/trenchesdeveloper/go-ai-store/internal/dto"
)

// Quantity is the resolver for the quantity field.
func (r *cartItemResolver) Quantity(ctx context.Context, obj *dto.CartItemResponse) (int32, error) {
	panic(fmt.Errorf("not implemented: Quantity - quantity"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *orderResolver) CreatedAt(ctx context.Context, obj *dto.OrderResponse) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// Quantity is the resolver for the quantity field.
func (r *orderItemResolver) Quantity(ctx context.Context, obj *dto.OrderItemResponse) (int32, error) {
	panic(fmt.Errorf("not implemented: Quantity - quantity"))
}

// Stock is the resolver for the stock field.
func (r *productResolver) Stock(ctx context.Context, obj *dto.ProductResponse) (int32, error) {
	panic(fmt.Errorf("not implemented: Stock - stock"))
}

// CartItem returns graph.CartItemResolver implementation.
func (r *Resolver) CartItem() graph.CartItemResolver { return &cartItemResolver{r} }

// Order returns graph.OrderResolver implementation.
func (r *Resolver) Order() graph.OrderResolver { return &orderResolver{r} }

// OrderItem returns graph.OrderItemResolver implementation.
func (r *Resolver) OrderItem() graph.OrderItemResolver { return &orderItemResolver{r} }

// Product returns graph.ProductResolver implementation.
func (r *Resolver) Product() graph.ProductResolver { return &productResolver{r} }

type cartItemResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
