package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"time"

	"github.com/trenchesdeveloper/go-ai-store/graph"
	"github.com/trenchesdeveloper/go-ai-store/internal/dto"
)

// ID is the resolver for the id field.
func (r *cartItemResolver) ID(ctx context.Context, obj *dto.CartItemResponse) (uint, error) {
	return obj.ID, nil
}

// Quantity is the resolver for the quantity field.
func (r *cartItemResolver) Quantity(ctx context.Context, obj *dto.CartItemResponse) (int32, error) {
	return int32(obj.Quantity), nil
}

// ID is the resolver for the id field.
func (r *orderResolver) ID(ctx context.Context, obj *dto.OrderResponse) (uint, error) {
	return obj.ID, nil
}

// UserID is the resolver for the userId field.
func (r *orderResolver) UserID(ctx context.Context, obj *dto.OrderResponse) (uint, error) {
	return obj.UserID, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *orderResolver) CreatedAt(ctx context.Context, obj *dto.OrderResponse) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339, obj.CreatedAt)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// ID is the resolver for the id field.
func (r *orderItemResolver) ID(ctx context.Context, obj *dto.OrderItemResponse) (uint, error) {
	return obj.ID, nil
}

// Quantity is the resolver for the quantity field.
func (r *orderItemResolver) Quantity(ctx context.Context, obj *dto.OrderItemResponse) (int32, error) {
	return int32(obj.Quantity), nil
}

// ID is the resolver for the id field.
func (r *productResolver) ID(ctx context.Context, obj *dto.ProductResponse) (uint, error) {
	return obj.ID, nil
}

// CategoryID is the resolver for the categoryId field.
func (r *productResolver) CategoryID(ctx context.Context, obj *dto.ProductResponse) (uint, error) {
	return obj.CategoryID, nil
}

// Stock is the resolver for the stock field.
func (r *productResolver) Stock(ctx context.Context, obj *dto.ProductResponse) (int32, error) {
	return int32(obj.Stock), nil
}

// ID is the resolver for the id field.
func (r *productImageResolver) ID(ctx context.Context, obj *dto.ProductImageResponse) (uint, error) {
	return obj.ID, nil
}

// ID is the resolver for the id field.
func (r *cartResolver) ID(ctx context.Context, obj *dto.CartResponse) (uint, error) {
	return obj.ID, nil
}

// UserID is the resolver for the userId field.
func (r *cartResolver) UserID(ctx context.Context, obj *dto.CartResponse) (uint, error) {
	return obj.UserID, nil
}

// CartItem returns graph.CartItemResolver implementation.
func (r *Resolver) CartItem() graph.CartItemResolver { return &cartItemResolver{r} }

// Order returns graph.OrderResolver implementation.
func (r *Resolver) Order() graph.OrderResolver { return &orderResolver{r} }

// OrderItem returns graph.OrderItemResolver implementation.
func (r *Resolver) OrderItem() graph.OrderItemResolver { return &orderItemResolver{r} }

// Product returns graph.ProductResolver implementation.
func (r *Resolver) Product() graph.ProductResolver { return &productResolver{r} }

type cartItemResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type productImageResolver struct{ *Resolver }
type cartResolver struct{ *Resolver }
