package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"github.com/trenchesdeveloper/go-ai-store/graph"
	"github.com/trenchesdeveloper/go-ai-store/internal/dto"
)

// Quantity is the resolver for the quantity field.
func (r *cartItemResolver) Quantity(ctx context.Context, obj *dto.CartItemResponse) (int32, error) {
	return int32(obj.Quantity), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *cartItemResolver) UpdatedAt(ctx context.Context, obj *dto.CartItemResponse) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// Quantity is the resolver for the quantity field.
func (r *orderItemResolver) Quantity(ctx context.Context, obj *dto.OrderItemResponse) (int32, error) {
	return int32(obj.Quantity), nil
}

// Stock is the resolver for the stock field.
func (r *productResolver) Stock(ctx context.Context, obj *dto.ProductResponse) (int32, error) {
	return int32(obj.Stock), nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *productImageResolver) CreatedAt(ctx context.Context, obj *dto.ProductImageResponse) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// CartItem returns graph.CartItemResolver implementation.
func (r *Resolver) CartItem() graph.CartItemResolver { return &cartItemResolver{r} }

// OrderItem returns graph.OrderItemResolver implementation.
func (r *Resolver) OrderItem() graph.OrderItemResolver { return &orderItemResolver{r} }

// Product returns graph.ProductResolver implementation.
func (r *Resolver) Product() graph.ProductResolver { return &productResolver{r} }

// ProductImage returns graph.ProductImageResolver implementation.
func (r *Resolver) ProductImage() graph.ProductImageResolver { return &productImageResolver{r} }

type cartItemResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type productImageResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *cartResolver) CreatedAt(ctx context.Context, obj *dto.CartResponse) (*time.Time, error) {
	return &obj.CreatedAt, nil
}
func (r *cartResolver) UpdatedAt(ctx context.Context, obj *dto.CartResponse) (*time.Time, error) {
	return &obj.UpdatedAt, nil
}
func (r *cartItemResolver) CreatedAt(ctx context.Context, obj *dto.CartItemResponse) (*time.Time, error) {
	return &obj.CreatedAt, nil
}
func (r *categoryResolver) CreatedAt(ctx context.Context, obj *dto.CategoryResponse) (*time.Time, error) {
	return &obj.CreatedAt, nil
}
func (r *categoryResolver) UpdatedAt(ctx context.Context, obj *dto.CategoryResponse) (*time.Time, error) {
	return &obj.UpdatedAt, nil
}
func (r *orderResolver) CreatedAt(ctx context.Context, obj *dto.OrderResponse) (*time.Time, error) {
	return &obj.CreatedAt, nil
}
func (r *orderResolver) UpdatedAt(ctx context.Context, obj *dto.OrderResponse) (*time.Time, error) {
	return &obj.UpdatedAt, nil
}
func (r *orderItemResolver) CreatedAt(ctx context.Context, obj *dto.OrderItemResponse) (*time.Time, error) {
	return &obj.CreatedAt, nil
}
func (r *productResolver) CreatedAt(ctx context.Context, obj *dto.ProductResponse) (*time.Time, error) {
	return &obj.CreatedAt, nil
}
func (r *productResolver) UpdatedAt(ctx context.Context, obj *dto.ProductResponse) (*time.Time, error) {
	return &obj.UpdatedAt, nil
}
func (r *productImageResolver) UpdatedAt(ctx context.Context, obj *dto.ProductImageResponse) (*time.Time, error) {
	return &obj.UpdatedAt, nil
}
func (r *userResolver) CreatedAt(ctx context.Context, obj *dto.UserResponse) (*time.Time, error) {
	return &obj.CreatedAt, nil
}
func (r *userResolver) UpdatedAt(ctx context.Context, obj *dto.UserResponse) (*time.Time, error) {
	return &obj.UpdatedAt, nil
}
func (r *Resolver) Cart() graph.CartResolver { return &cartResolver{r} }
func (r *Resolver) Category() graph.CategoryResolver { return &categoryResolver{r} }
func (r *Resolver) Order() graph.OrderResolver { return &orderResolver{r} }
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }
type cartResolver struct{ *Resolver }
type categoryResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
*/
